version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: deliveryrentals-db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - deliveryrentals-net

volumes:
  postgres_data:

networks:
  deliveryrentals-net:
    driver: bridge
